### ISSUE TITLE
Do we need a table in parents.md?

### ISSUE THREAD

**Issue by shymega** [zleap/ttj_website_development#13]
On this [link](https://github.com/zleap/ttj_website_development/blame/master/parents.md#L107), we have a note added by @zleap, for adding a table of comparisons between this services.

I don't think it's necessary to replicate information _already_ extensively documented elsewhere on the internet.

It would be better to just link to a existing page on this.

Thoughts?

**Comment by zleap** [comment]
We have been asked to make it clear on the differences,  sure it is documetned else where but parents need to see at a glance,   if we want to link to further info then we can.  but the info should all be in _one_ place,  parents are putting trust in US to provide accurate information on a range of topics here,

**Comment by shymega** [comment]
Hello,

Paul Sutton <notifications@github.com> writes:

> We have been asked to make it clear on the differences, sure it is
> documetned else where but parents need to see at a glance, if we
> want to link to further info then we can.  but the info should all
> be in _one_ place, parents are putting trust in US to provide
> accurate information on a range of topics here,

Yes, I agree.

I think a clear *balance* is needed here. We don't want to replicate
*too* much, but OTOH, we do not want to replicate too _little_.

As long as we all keep a balance, then extensive replication may not
be a huge concern.

Best regards,
--
Dom Rodriguez

**Comment by harleyyyyymayes** [comment]
There is no longer a table
