### ISSUE TITLE
hardware.md has info on FS.

### ISSUE THREAD

**Issue by shymega** [zleap/ttj_website_development#14]
The hardware.md document has information about types of file systems. 

Considering this document is _for_ h/w, why are we including information there, of all places?

File systems, AFAIK, are irrelevant to hardware - at least in the context of hardware.md.

(Offending lines: L99-L100)

Thoughts?

**Comment by zleap** [comment]
Where should it be then ?

**Comment by mlugg** [comment]
Valid point - will look at this in a bit, and move it.

**Comment by shymega** [comment]
Hello,

mlugg <notifications@github.com> writes:

> Valid point - will look at this in a bit, and move it.

Good - thanks a lot!

Best regards,
--
Dom Rodriguez

**Comment by shymega** [comment]
Hi,

Paul Sutton <notifications@github.com> writes:

> Where should it be then ?

Probably in a software page, or one about filesystems and/or computer
internals..

Best regards,
--
Dom Rodriguez

**Comment by mlugg** [comment]
Completely forgot about this - sorry! Can @harleyyyyymayes scream at me tomorrow to fix it, so I don't forget?

**Comment by shymega** [comment]
Hello,

mlugg <notifications@github.com> writes:

> Completely forgot about this - sorry! Can @harleyyyyymayes scream at
> me tomorrow to fix it, so I don't forget?

I think that's possible to arrange ;-)

Audio recording or it didn't happen!

-- 
Best regards,
Dom Rodriguez

**Comment by shymega** [comment]
@mlugg How's this going? I haven't seen any commits from you that would rectify this.

**Comment by mlugg** [comment]
I have resolved this with my latest commit, although important information on Linux filesystems should be moved to that page instead of being linked and there is currently no information on Mac OS filesystems.

**Comment by harleyyyyymayes** [comment]
This is gone.
