### ISSUE TITLE
Adjustments needed to parents.md

### ISSUE THREAD

**Issue by zleap** [zleap/ttj_website_development#15]
`parents.md` page needs the following adjustments:

ZNC / IRCCloud information needs checking to make sure it is correct.
I tried to explain the best that I can.

We need to make it _clear_ with regards to Github, Gitorious, Gitolite, and Notabug - what the deal is with free accounts, public accounts, private accounts and other concepts.
We should also mention that Github provides free private accounts for students, which are normally $7 a month.   

I have suggested a comparison table for this .

Remember that it is parents who are going to pay for private accounts. so if this is not needed, we need to make the choices / options clear.

**Comment by shymega** [comment]
Hello,

Paul Sutton <notifications@github.com> writes:

> Parents,md page needs the following please
>
> ZNC / IRC cloud information needs checking to make sure it is
> correct . I tried to explain best I can.
>
> we need to make it _clear_ with regard to github, gitorious,
> gitolite, and notabug l, what the deal is, with free accounts,
> public accounts, private accounts etc, and mention that github
> provides free private accounts for schools for $7 a month.  I have
> suggested a comparison table for this
>
> Remember that it is parents who are going to pay for private
> accounts if this is not needed we need to make the choices / options
> clear.

Edited your issue, clarified points and fixed grammatical errors.

The title should probably be changed to a more descriptive title as
well - perhaps: "Parents page improvements".

I can't change the title, as you are the owner of this repository.

Best regards,
--
Dom Rodriguez

**Comment by shymega** [comment]
Closing, this issue was fixed.
