### ISSUE TITLE
Address .md linting results, cure and resolve

### ISSUE THREAD

**Issue by shymega** [zleap/ttj_website_development#16]
I have taken the liberty of running [mdl](https://github.com/mivok/markdownlint) on the
ttj_website_development repository.

This tool lints the Markdown files, and reports any mistakes.
I have also included a script to automatically do this, made by
myself.

There are 438 lint errors in the repo alone.
I recommend that we make this a _blocking_ issue, before we migrate to
the new website. It is important to resolve this errors.

The results can be found [here](https://git.io/vioFn), and I'm sure you'll all
have no trouble understanding them.

I will be working on this as well.

**Comment by shymega** [comment]
All contributors - feel free to assign yourselves to this.

Any help will be appreciated, be that via PR's, direct push, whatever.

Feel free to talk about it on IRC - channel #torbaytechjam.

**Comment by shymega** [comment]
I have been working solely on the linting issues, and within a couple
of weeks, I have managed to bring down the count of lint issues to
around 29, from ~439 lint issues, which is good.

The main ones to fix now are:

- irc.md
- FLOSS.md
- welcome.md

FLOSS.md needs a rewrite anyway, so I will be opening an issue for
that.

irc.md needs an improvement on the table. At the moment, it's verbose,
and exceeds 72 characters.

welcome.md has inline HTML, which is *not* necessary. I will be
creating an issue for that too.

**Comment by shymega** [comment]
Opened issues for the three issues mentioned above.

**Comment by harleyyyyymayes** [comment]
@shymega Please look

**Comment by shymega** [comment]
Mostly fixed them all, the only thing left now is irc.md. But that will require a refactor.

**Comment by mlugg** [comment]
I'll work on irc.md in a sec.

**Comment by shymega** [comment]
@mlugg Alright, thanks. Request: KISS it.

**Comment by mlugg** [comment]
... Wat

**Comment by mlugg** [comment]
I have made the table as concise as I can do. If you feel anything can be shortened, feel free to do so.

**Comment by shymega** [comment]
@mlugg Keep it simple, stupid. That's what I mean by KISS it.

**Comment by shymega** [comment]
Closing, we have fixed the lint errors.
