### ISSUE TITLE
Improve irc.md commands table

### ISSUE THREAD

**Issue by shymega** [zleap/ttj_website_development#18]
At the moment, irc.md's command table is long, exceeds 72 characters
width, and provides excessive information.

Additionally, nearly all of the commands listed there are also listed
countless other times.

IMHO, it would be better off kept on the vKTec IRC website instead,
keeping this site small and focused.

**Comment by harleyyyyymayes** [comment]
Hello,



I think the table should stay. Most people won't go to the vKTec IRC site from the TTJ, if they're not the most savvy, or just want to connect,

so this table does serve a purpose, as well as Matthew spending an hour on it (not kidding



-Harley Mayes

https://harleyyyyymayes.uk



---- On Sun, 09 Oct 2016 14:19:53 +0000Dom Rodriguez &lt;notifications@github.com&gt; wrote ----




At the moment, irc.md's command table is long, exceeds 72 characters

 width, and provides excessive information.


Additionally, nearly all of the commands listed there are also listed

 countless other times.


IMHO, it would be better off kept on the vKTec IRC website instead,

 keeping this site small and focused.

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> I think the table should stay. Most people won't go to the vKTec IRC
> site from the TTJ, if they're not the most savvy, or just want to
> connect,

Good point.

> so this table does serve a purpose, as well as Matthew spending an
> hour on it (not kidding

..I actually worked on this table as well - on the WP site, anyway, I
presume this is derived from that..

Anyways, how about we try and slim down the verbosity of it? Or
perhaps we could make a separate page for the commands, so the irc.md
page is more concise and simplistic.

-- 
Best regards,
Dom Rodriguez

**Comment by mlugg** [comment]
The hour I spent on this was just the table formatting - I'm more than happy to make it more concise (I actually had the same thought when moving the info), although I think it should stay on the TTJ site as even if you don't use vKTec, IRC is still very useful, and is a good way to get in touch with use. Also, I'm alive :D

**Comment by shymega** [comment]
Hello,

mlugg <notifications@github.com> writes:

> The hour I spent on this was just the table formatting - I'm more
> than happy to make it more concise (I actually had the same thought
> when moving the info),

Ah. I see.

That's interesting to see we were on the same lines of thought :-)

> although I think it should stay on the TTJ site as even if you don't
> use vKTec, IRC is still very useful, and is a good way to get in
> touch with use.

Agreed.

> Also, I'm alive :D

I had no doubts of this :-)

Now, in terms of the next steps, I would say it would be great if you
could make the irc.md page more concise.

Shall I assign this issue to you?

-- 
Best regards,
Dom Rodriguez

**Comment by shymega** [comment]
@mlugg I'm waiting for an answer- what do you think about making the irc.md page more concise?

**Comment by mlugg** [comment]
Sorry, I've been somewhat distracted. And I may or may not have forgotten entirely. I'll assign myself and sort this now (after installing the Win10 Anniversary Update so I can access my VPS natively) alongside hardware.md (see issue #14 )

**Comment by mlugg** [comment]
Sorted, kind of. Some I had trouble shortening, but for the most part the table is now more concise - however I may take a look at this again in the future, and if anyone wants to take a look in the meantime, yay, less work for me.

**Comment by harleyyyyymayes** [comment]
Hello, this table has been made more concise etc. I am closing this issue.
