### ISSUE TITLE
welcome.md has inline HTML

### ISSUE THREAD

**Issue by shymega** [zleap/ttj_website_development#19]
As @vktec has said on IRC, Markdown doesn't need HTML used in
Markdown. I think he said it could be done with CSS, if memory serves
me correctly.

Noting that, I'd say we should remove the HTML in welcome.md.

Centering isn't, in my view, necessary, and makes the page look a bit
"desperate" for attention.

Thoughts?

**Comment by harleyyyyymayes** [comment]
Hello,



Personally, I think the centering looks nice, seeing as it's the main page title,

but that's my opinion.

Again, I'll be showing a "preview" site at a future Jam for feedback :)



-Harley Mayes

https://harleyyyyymayes.uk

---- On Sun, 09 Oct 2016 14:20:59 +0000Dom Rodriguez &lt;notifications@github.com&gt; wrote ----




As @vktec has said on IRC, Markdown doesn't need HTML used in

 Markdown. I think he said it could be done with CSS, if memory serves

 me correctly.


Noting that, I'd say we should remove the HTML in welcome.md.

Centering isn't, in my view, necessary, and makes the page look a bit

 "desperate" for attention.


Thoughts?

**Comment by vktec** [comment]
On 09/10/16 19:14, Harley Mayes wrote:
> Hello,
>
> Personally, I think the centering looks nice, seeing as it's the main
> page title, but that's my opinion.

Whether centering looks nice or not is a moot point. What I said wasn't 
that we shouldn't have centering, it was that we shouldn't care about 
that when writing content. If we collectively decide we want to center 
the page title, then we can do that... in a **stylesheet**.

Markdown is for content, HTML is for layout, CSS is for styling. Since 
this is a styling issue, it's CSS territory and should not be handled in 
Markdown.

> Again, I'll be showing a "preview" site at a future Jam for feedback :)
>
> -Harley Mayes
>
> https://harleyyyyymayes.uk
>
> ---- On Sun, 09 Oct 2016 14:20:59 +0000Dom Rodriguez
>> <notifications@github.com> wrote ----
>>
>> As @vktec has said on IRC, Markdown doesn't need HTML used in
>> Markdown. I think he said it could be done with CSS, if memory serves
>> me correctly.
>>
>> Noting that, I'd say we should remove the HTML in welcome.md.
>>
>> Centering isn't, in my view, necessary, and makes the page look a bit
>> "desperate" for attention.
>>
>> Thoughts?

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> Hello,
>
> Personally, I think the centering looks nice, seeing as it's the
> main page title, but that's my opinion.

I respect your opinion :-) My opinion of it is that it looks cr**py,
but hey, opinions are fun, amirite?

Bear in mind that the page title will be at the top of the page anyway
- so it's not *really* necessary for the centered text, y'know?

See this[1] post from my blog - notice it has the title at the top?

> Again, I'll be showing a "preview" site at a future Jam for feedback
> :)

Can I presume you'll want a running demo of the site for that?

If you do, let me know in advance (at least a month!), and I'll see if
I can whip up the site on my server for you, OK? Cheers.

Or, alternatively - you *can* build the site yourself. You just need
Haskell platform, time and willingness to compile ~115 libraries, and
then to compile the static site.

[1]: https://blog.shymega.org.uk/posts/announcing-slacs.html

-- 
Best regards,
Dom Rodriguez

**Comment by mlugg** [comment]
I agree with shymega and vktec here - I don't think it looks very good / professional, and even so as vktec said it's a CSS issue. it has also broken the Markdown headers, at least for me.

**Comment by harleyyyyymayes** [comment]
Inline HTML has been removed
