### ISSUE TITLE
FLOSS.md needs to be rewritten to be more concise

### ISSUE THREAD

**Issue by shymega** [zleap/ttj_website_development#20]
At the moment, FLOSS.md is excessively written, verbose and (IMHO)
hard to understand for some members of the Tech Jam.

We need to rewrite it to be less verbose and more simplistic, but with
a clear balance between the two attributes.

Any takers?

**Comment by harleyyyyymayes** [comment]
Hello,

I spent about 30-60 mins copying this off the old site.

I think it may be okay to stay the same, but I'll do a "talk" at a future jam, with these new pages on a "preview" site.

This would be to get feedback.



-Harley Mayes

https://harleyyyyymayes.uk



---- On Sun, 09 Oct 2016 14:22:14 +0000Dom Rodriguez &lt;notifications@github.com&gt; wrote ----




At the moment, FLOSS.md is excessively written, verbose and (IMHO)

 hard to understand for some members of the Tech Jam.


We need to rewrite it to be less verbose and more simplistic, but with

 a clear balance between the two attributes.


Any takers?

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> I spent about 30-60 mins copying this off the old site.

> I think it may be okay to stay the same, but I'll do a "talk" at a
> future jam, with these new pages on a "preview" site.
> This would be to get feedback.

Even though its been copied off the old site, that doesn't mean it's
good to stay, y'know?

I recall that @zleap commented to me that the FLOSS.md page was very
verbose, so I'm inclined to say it *does* need rewriting, at least to
make it more concise.

It feels like a Wikipedia page.. that's not what we want, surely?

Also, we should aim to provide references for our sources :-)

Hakyll's markdown supports referencing as well.

-- 
Best regards,
Dom Rodriguez

**Comment by shymega** [comment]
@harleyyyyymayes @zleap @mlugg @vktec Hello all- any other thoughts on this page?

**Comment by harleyyyyymayes** [comment]
@mlugg @vktec @shymega -- Could one of you please have a look at doing this please?

**Comment by vktec** [comment]
Sure, I can do this now

**Comment by vktec** [comment]
Christ! 200 lines!

**Comment by vktec** [comment]
Okay, updated. Any comments?

**Comment by vktec** [comment]
I'm gonna close this, as I think it's pretty much done. Let me know if there's anything else I should add.
