### ISSUE TITLE
Add information on macOS Filesystems.

### ISSUE THREAD

**Issue by zleap** [zleap/ttj_website_development#7]
We now have a section on Linux / Windows file systems,  we could do with one on  Mac based file systems for completeness.

Also we should not add too many for Linux,  as it supports hundreds and we will just end up overloading people with information.

**Comment by harleyyyyymayes** [comment]
I will get on this, although some help from @vktec is welcome

**Comment by harleyyyyymayes** [comment]
@vktec @mlugg

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> @vktec @mlugg

You last posted a request for help 8 hours ago.

I'm sure @vktec or @mlugg have got that message - now is a time for
waiting for help.

Thanks.

-- 
Best regards,
Dom Rodriguez

**Comment by harleyyyyymayes** [comment]
@shymega Woah, I was with @mlugg when I mentioned him. sorry

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> @shymega Woah, I was with @mlugg when I mentioned him. sorry

No problem :-)

-- 
Best regards,
Dom Rodriguez

**Comment by zleap** [comment]
I agree with not adding too many,  just the common ones + a link to further reading

**Comment by harleyyyyymayes** [comment]
@mlugg -- You have assigned this to yourself, yet not actually done anything, please take a look

**Comment by mlugg** [comment]
@harleyyyyymayes <sarcasm> Sorry, Mum. </sarcasm> But good point, I will get on this

**Comment by shymega** [comment]
This was fixed with commit ab3d6ffa7e38cb3c9bbe91f055f181dee82468bf, closing.
