### ISSUE TITLE
Fill out Policies

### ISSUE THREAD

**Issue by harleyyyyymayes** [zleap/ttj_website_development#8]
I am on a spree of copying pages over, and noticed the POLICIES page on the current website is blank. I have still copied it over though. Please could you fill out policies.md I will assign this to @zleap but if anyone else is willing to do this, then comment or self assign yourself

**Comment by shymega** [comment]
Hello,

Harley Mayes <notifications@github.com> writes:

> I am on a spree of copying pages over, and noticed the POLICIES page
> on the current website is blank. I have still copied it over
> though. Please could you fill out policies.md I will assign this to
> @zleap but if anyone else is willing to do this, then comment or
> self assign yourself

OK, looks good :-)

-- 
Best regards,
Dom Rodriguez

**Comment by zleap** [comment]
there should be links to the safeguarding page,  now,  however I an not a safeguarding lead so am just struggling to know what to write,  so this is yet another reason we need more _help_ with this,
